[profile.release]
panic = "unwind"

[workspace]
members = [
    "node",
    "pallets/*",
    "runtime",
]
resolver = "2"

[workspace.package]
authors = ["Anonymous"]
edition = "2021"
homepage = "https://magnet.magport.io/"
license = "Unlicense"
repository = "https://github.com/Magport/Magnet"
